a = float(input("Enter num 1:"))
b = float(input("Enter num 2:"))

print(f"a + b = {a+ b}")
print(f"a - b = {a- b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"a % b = {a % b}")
print(f"a // b = {a // b}")
print(f"a ^ b = {a**b}")
